### ISSUE TITLE
Wrong schema for indexedMzML?

### ISSUE THREAD

**Issue by jpfeuffer** [compomics/ThermoRawFileParser#71] opened 2020-04-06 11:01 UTC
Hi!

I get the following header
```
<?xml version="1.0" encoding="utf-8"?>
<indexedmzML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.0.xsd" xmlns="http://psi.hupo.org/ms/mzml">
  <mzML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.0.xsd" version="1.1.0" id="20120415_EXQ5_KiSh_SA_LabelFree_HeLa_pY_Noco_rep1">
    <cvList count="2">
...
```
when I run with "-f2"

Should it maybe be
```
<indexedmzML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.2_idx.xsd" xmlns="http://psi.hupo.org/ms/mzml">
...
```
 or similar?

**Comment by nielshulstaert** [comment] 2020-05-04 08:51
Hi, my apologies for the late reply. Indeed the indexed schema used is 1.1.1 so I could change it to 

`<indexedmzML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.1_idx.xsd" xmlns="http://psi.hupo.org/ms/mzml">`

int the next release. I didn't find any 1.1.2 version, could you point me to it?

**Comment by jpfeuffer** [comment] 2020-05-04 09:09
Hi! I am actually not sure anymore where I got it from 😄 I think I compared with msConvert. Let me check if 1.1.2 was correct.
My main point was the "_idx" suffix, I think.

**Comment by ypriverol** [comment] 2020-05-12 10:18
The mzML schemas are here: 

- index:  https://raw.githubusercontent.com/HUPO-PSI/mzML/master/schema/schema_1.1/mzML1.1.1_idx.xsd

- non-index: https://raw.githubusercontent.com/HUPO-PSI/mzML/master/schema/schema_1.1/mzML1.1.0.xsd

**Comment by jpfeuffer** [comment] 2020-05-12 10:28
Ok there is no 1.1.2 yet, right?

**Comment by ypriverol** [comment] 2020-05-12 10:30
The main problem we have here is that we are using URLs like: 

```
http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.1_idx.xsd
```
This is wrong because is not a proper URL.

**Comment by edeutsch** [comment] 2020-05-12 16:08
As far as I'm aware, there is no 1.1.2. The latest schemas are listed here:
https://github.com/HUPO-PSI/mzML/tree/master/schema/schema_1.1

However, in looking at an output mzML files from msconvert, I see:
<indexedmzML xmlns="http://psi.hupo.org/ms/mzml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psi
.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.2_idx.xsd">

To make matters weirder, this URI:
http://psidev.info/files/ms/mzML/xsd/mzML1.1.2_idx.xsd
is a valid redirect to the 1.1.1 schema. While this URI:
http://psidev.info/files/ms/mzML/xsd/mzML1.1.1_idx.xsd
yields a 404.

Does @chambm or @javizca have any historical memory of this? Seems like the URI should be:
http://psidev.info/files/ms/mzML/xsd/mzML1.1.1_idx.xsd
and that should be a redirect to:
https://raw.githubusercontent.com/HUPO-PSI/mzML/master/schema/schema_1.1/mzML1.1.1_idx.xsd

What do you think?

**Comment by chambm** [comment] 2020-05-12 16:20
@edeutsch I'm afraid this may be an action item 8 years overdue :)
https://sourceforge.net/p/psidev/mailman/psidev-ms-dev/thread/50D17F1D.9090508%40immun.lth.se/#msg30249870

**Comment by edeutsch** [comment] 2020-05-12 20:12
haha, I have taken slothfulness to a new level!

I propose to check in mzML1.1.2_idx.xsd. I found a copy of it. And then I will ask @javizca to update the hyperlinks at psidev.info.

It looks like ProteoWizard has already implemented this for many years. And then we'll get ThermoRawFileParser to do the same.

Any objections?

**Comment by ypriverol** [comment] 2020-05-12 20:14
@edeutsch actually you can do just a PR to github. We need to update the URLs in the library to github because the psi URLs are not working. 

This goes nowhere http://psidev.info/files/ms/mzML/xsd/mzML1.1.1_idx.xsd

**Comment by edeutsch** [comment] 2020-05-12 20:18
@ypriverol I can certainly do a PR instead of direct checkin if you prefer that.

Although this goes nowhere:
http://psidev.info/files/ms/mzML/xsd/mzML1.1.1_idx.xsd
This does:
http://psidev.info/files/ms/mzML/xsd/mzML1.1.2_idx.xsd
(although to 1.1.1)

Which is why I said that after we have GitHub fixed, we need to ask @javizca to fix psidev.info. Or maybe you can do that?

**Comment by edeutsch** [comment] 2020-05-12 20:30
okay chaps, I have created a PR at
https://github.com/HUPO-PSI/mzML/pulls
I would say that if we get approvals from @ypriverol and @chambm, we can merge it.

Sound okay?

**Comment by caetera** [comment] 2020-10-07 17:27
It seems like the issue is still not fixed.
Should I just update schema location to the current location on Github?

    index: https://raw.githubusercontent.com/HUPO-PSI/mzML/master/schema/schema_1.1/mzML1.1.1_idx.xsd

    non-index: https://raw.githubusercontent.com/HUPO-PSI/mzML/master/schema/schema_1.1/mzML1.1.0.xsd

**Comment by edeutsch** [comment] 2020-10-08 05:42
Sorry, I forgot to follow up on this.
@javizca, would you make the links:
http://psidev.info/files/ms/mzML/xsd/mzML1.1.1_idx.xsd   (currently a 404)
http://psidev.info/files/ms/mzML/xsd/mzML1.1.2_idx.xsd   (currently points to the wrong file)
do the right thing?

Correct content is in:
https://github.com/HUPO-PSI/mzML/tree/master/schema/schema_1.1

**Comment by caetera** [comment] 2022-10-21 17:26
This issue has not been active for quite a while, I will close it, but you're a welcome to reopen it if necessary.

**Closed by caetera** 2022-10-21 17:26 UTC
