### ISSUE TITLE
-s parameter fails to convert scan data

### ISSUE THREAD

**Issue by tomas-pluskal** [compomics/ThermoRawFileParser#118] opened 2021-05-17 13:22 UTC
Hi,
the -s parameter introduced after the discussion in #99 does not work in the latest version 1.3.4. (I have not tested previous releases so I don't know if it worked in the past and got broken at some point)

A simple test: I use a 15MB .raw file called a.raw.
After running `ThermoRawFileParser.exe -i a.raw` I get a complete mzML file a.mzML with comparable size (~10 MB).
When I run `ThermoRawFileParser.exe -s -i a.raw > a.mzML` the output file is tiny (~3 KB) and contains only the mzML header but no scan data.

**Comment by nielshulstaert** [comment] 2021-05-18 09:46
Hi Tomas thanks for reporting this, I'll have a look and get back to you.

**Comment by caetera** [comment] 2021-05-18 16:43
Hi Tomas, thank you for reporting. The cause of the error is likely because since 1.3.3 the default output format is **indexed** mzML, it is not possible to index piped output and thus TRFP crashes (I am actually surprised it does not spit any error or exception).
As quick work around, please, try using `-f=1` (regular mzML)

**Comment by nielshulstaert** [comment] 2021-05-18 17:18
Yes indeed I was looking for a fix but I didn't find one yet. @caetera indeed we need to at least mention it in de help output. As mentioned, it does work for all the other output formats, including the metadata.

**Comment by tomas-pluskal** [comment] 2021-05-18 20:31
I can confirm it works fine with the `-f=1` parameter.

**Comment by caetera** [comment] 2022-05-16 16:39
Closed in 410ff006b2592f95c7227af2418e281b3a79a35a.
STDOUT (`-s`) always forces **plain mzML** instead of **indexed mzML**

**Closed by caetera** 2022-05-16 16:39 UTC
